#ifndef LIB_H
#define LIB_H

#include "./ADT/Graf/graf.h"
#include "./ADT/LinkedList/listlinier.h"
#include "./ADT/ListDinamik/listdinamik.h"
#include "./ADT/ListStatik/liststatik.h"
#include "./ADT/Matriks/matriks.h"
#include "./ADT/String/string.h"
#include "./ADT/WordMachine/wordmachine.h"
#include "./ADT/WordMachine/wordmachinefile.h"
#include "./ADT/Queue/queue.h"
#include "./ADT/Stack/stack.h"
#include "./ADT/Tree/tree.h"
#include "./ADT/PColor/pcolor.h"
#include "./boolean.h"
#include "./Types/Application/Application.h"
#include "./Types/Application/balasan/balasan.h"
#include "./Types/Application/balasan/balasan.h"
#include "./Types/Application/draf-kicauan/draf-kicauan-din.h"
#include "./Types/Application/inisialisasi/inisialisasi.h"
#include "./Types/Application/kicauan/kicauan.h"
#include "./Types/Application/pengguna/pengguna.h"
#include "./Types/Application/profil/profil.h"
#include "./Types/Application/simpan-dan-muat/muat.h"
#include "./Types/Application/permintaan-pertemanan/permintaan-pertemanan.h"
#include "./Types/Application/teman/teman.h"
#include "./Types/Application/utas/utas.h"
#include "./Types/Application/perintah/perintah.h"
#include "./Types/Application/Devtools.h"

#endif